// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyEz.Repositories.Entities;

public partial class FinancialGoal : BaseEntity
{
    public Guid UserId { get; set; }

    public Guid? GroupId { get; set; }

    public string Name { get; set; }

    public string NameUnsign { get; set; }

    public decimal TargetAmount { get; set; }

    public decimal? CurrentAmount { get; set; }

    public DateOnly Deadline { get; set; }

    public virtual GroupFund Group { get; set; }

    public virtual User User { get; set; }
}