// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyEz.Repositories.Entities;

public partial class GroupMember : BaseEntity
{
    public Guid GroupId { get; set; }

    public Guid UserId { get; set; }

    public decimal? ContributionPercentage { get; set; }

    public int? Role { get; set; }

    public int? Status { get; set; }

    public virtual GroupFund Group { get; set; }

    public virtual ICollection<GroupMemberLog> GroupMemberLogs { get; set; } = new List<GroupMemberLog>();

    public virtual User User { get; set; }
}