// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyEz.Repositories.Entities;

public partial class Notification : BaseEntity
{
    public bool? IsRead { get; set; }

    public string Title { get; set; }

    public string TitleUnsign { get; set; }

    public string Message { get; set; }

    public Guid? EntityId { get; set; }

    public Guid? UserId { get; set; }

    public int? Type { get; set; }

    public virtual User User { get; set; }
}