name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create firebase-adminsdk.json
        run: |
            mkdir -p ./MoneyEz.API
            echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > ./MoneyEz.API/firebase-adminsdk.json

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (optional, required if pushing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true  # Set to true to push the image to a registry
          tags: |
            ducdang03/money-ez:latest
  deploy:
    runs-on: self-hosted
    needs: docker-build

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Clean up old Docker resources
        run: |
          docker stop money-ez-api || true
          docker rm money-ez-api || true
    
      - name: Deploy to VPS
        run: |
          docker pull ducdang03/money-ez:latest
          docker run -d --name money-ez-api -p 8080:8080 ducdang03/money-ez:latest
  
      - name: Verify running containers
        run: docker ps -a